name: id_card
description: "A new Flutter project."
# Prevent accidental publishing to pub.dev
publish_to: 'none'

# Version and build number
version: 1.0.0+1

# Flutter SDK version
environment:
  sdk: ">=3.5.4 <4.0.0"

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

# Flutter-specific configuration
flutter:
  # Assets
  assets:
    - assets/IMG_5222.PNG

  # Ensures Material Icons are included
  uses-material-design: true
